spring.application.name=PetAdoption

spring.datasource.url=jdbc:mysql://localhost:3306/petAdoption
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=update